services:
  app:
    # user: "1000:1000"
    image: sipena-app:latest
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: sipena-app
    working_dir: /var/www/html
    volumes:
      #- app-data:/var/www/html # Production
      - ./src:/var/www/html # Development
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - sipena
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  reverb:
    image: sipena-app:latest
    container_name: sipena-reverb
    working_dir: /var/www/html
    # volumes:
    #   - ./src:/var/www/html
    command: php artisan reverb:start --port=3030
    ports:
      - "3030:3030"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - sipena

  nginx:
    image: nginx:alpine
    container_name: sipena-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- app-data:/var/www/html
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/assets.sipena.com.conf:/etc/nginx/conf.d/assets.sipena.com.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./nginx/ssl/rootCA.pem:/usr/local/share/ca-certificates/rootCA.pem
    depends_on:
      - app
    networks:
      - sipena
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.4
    container_name: sipena-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sipena
      MYSQL_USER: sipena
      MYSQL_PASSWORD: sipena
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sipena

  redis:
    image: redis:latest
    container_name: sipena-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sipena

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sipena-phpmyadmin
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: sipena
      PMA_PASSWORD: sipena
    networks:
      - sipena

  mailpit:
    image: axllent/mailpit
    container_name: sipena-mailpit
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - sipena

  minio:
    image: minio/minio
    container_name: sipena-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - sipena

networks:
  sipena:
    driver: bridge

volumes:
  app-data:
  mysql_data:
  minio_data:
